import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';

export type Lang = 'en' | 'id';

const en = {
  nav: {
    home: 'Home', submit: 'Submit',
    history: 'History', wallet: 'Wallet', profile: 'Profile',
  },
  home: {
    greeting:      'Good day',
    balance:       'Your Balance',
    locked:        'Locked',
    recentReports: 'Recent Reports',
    quickActions:  'Quick Actions',
    submitWaste:   'Submit Waste',
    viewWallet:    'View Wallet',
    noReports:     'No reports yet. Submit your first report!',
    earnPoints:    'Earn points',
    withdrawPoints:'Withdraw points',
    seeAll:        'See all',
  },
  submit: {
    title:          'Submit Report',
    subtitle:       'Fill in required fields',
    category:       'Waste Category',
    selectCategory: 'Select category…',
    earnPerUnit:    'Earn per',
    weight:         'Estimated Weight (kg)',
    estGross:       'Est. gross',
    handlingFee:    'Handling fee',
    estNet:         'Est. net points',
    weightNote:     '*Based on admin-verified weight',
    location:       'Location',
    detectGps:      'Detect my location',
    orTapMap:       'Or tap the map to pin your location · drag marker to adjust',
    address:        'Address',
    addressHint:    '(auto-filled from map)',
    pickupSchedule: 'Pickup Schedule',
    pickupDate:     'Pickup Date',
    pickupTime:     'Pickup Time',
    pickupHint:     '(07:00 – 17:00)',
    photos:         'Photos',
    photosHint:     '(optional, up to 5)',
    tapToAddPhotos: 'Tap to add photos',
    addMore:        'Add more',
    notes:          'Notes',
    notesHint:      '(optional)',
    notesPlaceholder: 'Any additional information…',
    submit:         'Submit Report',
    success:        'Report submitted successfully!',
    successTitle:   'Report Submitted!',
    successSub:     'Our team will validate it soon.',
    viewReports:    'View My Reports',
    submitAnother:  'Submit Another',
    confirmTitle:   'Submit This Report?',
    confirmBody:    'Once submitted, this report cannot be edited or undone. Our team will review and validate it shortly.',
    confirmYes:     'Yes, Submit',
    summaryCategory:'Category',
    summaryWeight:  'Est. Weight',
    summaryDate:    'Pickup Date',
    summaryTime:    'Pickup Time',
    summaryPhotos:  'Photos',
    summaryAttached:'attached',
    requiredNote:   'Please fill in all required fields',
  },
  history: {
    title:       'My Reports',
    empty:       'No reports found',
    all:         'All',
    estWeight:   'Est. Weight',
    actWeight:   'Actual Weight',
    netPoints:   'Net Points',
    fee:         'Handling Fee',
    gross:       'Gross Points',
    pointsEarned:'Points Earned',
    rejectionReason: 'Rejection Reason',
    noReason:    'No reason provided',
    submitted:   'Submitted',
    validated:   'Validated',
    pickupSchedule: 'Pickup Schedule',
    date:        'Date',
    time:        'Time',
    notes:       'Notes',
    noComments:  'No comments yet. Ask the admin about your report.',
    commentsTitle:'Comments with Admin',
    commentPlaceholder: 'Ask the admin something… (Enter to send)',
    adminLabel:  'Admin',
    previous:    'Previous',
    next:        'Next',
  },
  wallet: {
    title:         'My Wallet',
    available:     'Available Balance',
    locked:        'Locked (Pending)',
    withdraw:      'Request Withdrawal',
    eWallet:       'E-Wallet / Bank',
    accountNumber: 'Account / Phone Number',
    accountHolder: 'Account Holder Name',
    amount:        'Amount (points)',
    amountHint:    'max',
    myWithdrawals: 'Withdrawal History',
    noWithdrawals: 'No withdrawals yet',
    submitRequest: 'Submit Request',
    insufficientBalance: 'Insufficient balance',
    allRequired:   'All bank details are required',
    validAmount:   'Please enter a valid amount',
    submitted:     'Withdrawal request submitted!',
    ref:           'Ref',
    noBalance:     'You have no available balance to withdraw',
  },
  profile: {
    title:           'Profile',
    personalInfo:    'Personal Info',
    fullName:        'Full Name',
    phone:           'Phone',
    changePhoto:     'Change photo',
    uploading:       'Uploading…',
    changePassword:  'Change Password',
    currentPassword: 'Current Password',
    newPassword:     'New Password',
    confirmPassword: 'Confirm Password',
    updatePassword:  'Update Password',
    accountInfo:     'Account Info',
    email:           'Email',
    role:            'Role',
    memberSince:     'Member Since',
    signOut:         'Sign Out',
    signOutNote:     'You will be logged out of this device',
    cropTitle:       'Crop Photo',
    cropNote:        'Drag to reposition · Zoom with controls',
    usePhoto:        'Use This Photo',
    cropCancel:      'Cancel',
  },
  status: {
    pending:  'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    success:  'Success',
    all:      'All',
  },
  common: {
    save:    'Save',
    cancel:  'Cancel',
    loading: 'Loading…',
    logout:  'Logout',
    error:   'Something went wrong',
    back:    'Back',
    report:  'Report',
  },
  auth: {
    welcomeBack:     'Welcome back',
    email:           'Email',
    password:        'Password',
    signIn:          'Sign In',
    noAccount:       'Don\'t have an account?',
    register:        'Register',
    createAccount:   'Create account',
    fullName:        'Full Name',
    phone:           'Phone',
    optional:        '(optional)',
    minPassword:     'Min. 8 characters',
    haveAccount:     'Already have an account?',
    adminBlocked:    'This portal is for residents only. Please use the Admin Dashboard.',
    allRequired:     'Name, email and password are required',
    minChars:        'Password must be at least 8 characters',
    failed:          'Registration failed',
  },
};

const id: typeof en = {
  nav: {
    home: 'Beranda', submit: 'Lapor',
    history: 'Riwayat', wallet: 'Dompet', profile: 'Profil',
  },
  home: {
    greeting:      'Selamat datang',
    balance:       'Saldo Anda',
    locked:        'Terkunci',
    recentReports: 'Laporan Terbaru',
    quickActions:  'Aksi Cepat',
    submitWaste:   'Lapor Sampah',
    viewWallet:    'Lihat Dompet',
    noReports:     'Belum ada laporan. Kirim laporan pertama Anda!',
    earnPoints:    'Kumpulkan poin',
    withdrawPoints:'Tarik poin',
    seeAll:        'Lihat semua',
  },
  submit: {
    title:          'Kirim Laporan',
    subtitle:       'Isi kolom yang diperlukan',
    category:       'Kategori Sampah',
    selectCategory: 'Pilih kategori…',
    earnPerUnit:    'Poin per',
    weight:         'Estimasi Berat (kg)',
    estGross:       'Est. kotor',
    handlingFee:    'Biaya penanganan',
    estNet:         'Est. poin bersih',
    weightNote:     '*Berdasarkan berat yang diverifikasi admin',
    location:       'Lokasi',
    detectGps:      'Deteksi lokasi saya',
    orTapMap:       'Atau ketuk peta untuk menandai lokasi · seret penanda untuk menyesuaikan',
    address:        'Alamat',
    addressHint:    '(terisi otomatis dari peta)',
    pickupSchedule: 'Jadwal Pengambilan',
    pickupDate:     'Tanggal Pengambilan',
    pickupTime:     'Waktu Pengambilan',
    pickupHint:     '(07:00 – 17:00)',
    photos:         'Foto',
    photosHint:     '(opsional, maks. 5)',
    tapToAddPhotos: 'Ketuk untuk menambah foto',
    addMore:        'Tambah lagi',
    notes:          'Catatan',
    notesHint:      '(opsional)',
    notesPlaceholder: 'Informasi tambahan…',
    submit:         'Kirim Laporan',
    success:        'Laporan berhasil dikirim!',
    successTitle:   'Laporan Terkirim!',
    successSub:     'Tim kami akan memvalidasi segera.',
    viewReports:    'Lihat Laporan Saya',
    submitAnother:  'Kirim Laporan Lain',
    confirmTitle:   'Kirim Laporan Ini?',
    confirmBody:    'Setelah dikirim, laporan ini tidak dapat diubah atau dibatalkan. Tim kami akan meninjau dan memvalidasinya.',
    confirmYes:     'Ya, Kirim',
    summaryCategory:'Kategori',
    summaryWeight:  'Est. Berat',
    summaryDate:    'Tanggal Pengambilan',
    summaryTime:    'Waktu Pengambilan',
    summaryPhotos:  'Foto',
    summaryAttached:'terlampir',
    requiredNote:   'Harap isi semua kolom yang diperlukan',
  },
  history: {
    title:       'Laporan Saya',
    empty:       'Belum ada laporan',
    all:         'Semua',
    estWeight:   'Est. Berat',
    actWeight:   'Berat Aktual',
    netPoints:   'Poin Bersih',
    fee:         'Biaya Penanganan',
    gross:       'Poin Kotor',
    pointsEarned:'Poin Diperoleh',
    rejectionReason: 'Alasan Penolakan',
    noReason:    'Tidak ada alasan',
    submitted:   'Dikirim',
    validated:   'Divalidasi',
    pickupSchedule: 'Jadwal Pengambilan',
    date:        'Tanggal',
    time:        'Waktu',
    notes:       'Catatan',
    noComments:  'Belum ada komentar. Tanyakan ke admin tentang laporan Anda.',
    commentsTitle:'Komentar dengan Admin',
    commentPlaceholder: 'Tanyakan sesuatu ke admin… (Enter untuk kirim)',
    adminLabel:  'Admin',
    previous:    'Sebelumnya',
    next:        'Berikutnya',
  },
  wallet: {
    title:         'Dompet Saya',
    available:     'Saldo Tersedia',
    locked:        'Terkunci (Menunggu)',
    withdraw:      'Ajukan Penarikan',
    eWallet:       'E-Wallet',
    accountNumber: 'No. Rekening / HP',
    accountHolder: 'Nama Pemilik Rekening',
    amount:        'Jumlah (poin)',
    amountHint:    'maks',
    myWithdrawals: 'Riwayat Penarikan',
    noWithdrawals: 'Belum ada penarikan',
    submitRequest: 'Ajukan Permintaan',
    insufficientBalance: 'Saldo tidak cukup',
    allRequired:   'Semua detail dompet wajib diisi',
    validAmount:   'Masukkan jumlah yang valid',
    submitted:     'Permintaan penarikan berhasil dikirim!',
    ref:           'Ref',
    noBalance:     'Saldo Anda tidak cukup untuk melakukan penarikan',
  },
  profile: {
    title:           'Profil',
    personalInfo:    'Informasi Pribadi',
    fullName:        'Nama Lengkap',
    phone:           'Telepon',
    changePhoto:     'Ganti foto',
    uploading:       'Mengunggah…',
    changePassword:  'Ganti Kata Sandi',
    currentPassword: 'Kata Sandi Saat Ini',
    newPassword:     'Kata Sandi Baru',
    confirmPassword: 'Konfirmasi Kata Sandi',
    updatePassword:  'Perbarui Kata Sandi',
    accountInfo:     'Info Akun',
    email:           'Email',
    role:            'Peran',
    memberSince:     'Bergabung Sejak',
    signOut:         'Keluar',
    signOutNote:     'Anda akan keluar dari perangkat ini',
    cropTitle:       'Pangkas Foto',
    cropNote:        'Seret untuk memposisikan · Zoom dengan kontrol',
    usePhoto:        'Gunakan Foto Ini',
    cropCancel:      'Batal',
  },
  status: {
    pending:  'Menunggu',
    approved: 'Disetujui',
    rejected: 'Ditolak',
    success:  'Berhasil',
    all:      'Semua',
  },
  common: {
    save:    'Simpan',
    cancel:  'Batal',
    loading: 'Memuat…',
    logout:  'Keluar',
    error:   'Terjadi kesalahan',
    back:    'Kembali',
    report:  'Laporan',
  },
  auth: {
    welcomeBack:     'Selamat datang kembali',
    email:           'Email',
    password:        'Kata Sandi',
    signIn:          'Masuk',
    noAccount:       'Belum punya akun?',
    register:        'Daftar',
    createAccount:   'Buat akun',
    fullName:        'Nama Lengkap',
    phone:           'Telepon',
    optional:        '(opsional)',
    minPassword:     'Min. 8 karakter',
    haveAccount:     'Sudah punya akun?',
    adminBlocked:    'Portal ini hanya untuk warga. Gunakan Dashboard Admin.',
    allRequired:     'Nama, email, dan kata sandi wajib diisi',
    minChars:        'Kata sandi minimal 8 karakter',
    failed:          'Pendaftaran gagal',
  },
};

interface LangState {
  lang:    Lang;
  t:       (key: string) => string;
  setLang: (lang: Lang) => void;
}

export const useLangStore = create<LangState>()(
  persist(
    (set, get) => ({
      lang: 'id',
      t: (key: string) => {
        const keys   = key.split('.');
        const dict   = (get().lang === 'en' ? en : id) as any;
        let   result = dict;
        for (const k of keys) {
          result = result?.[k];
          if (result === undefined) return key;
        }
        return typeof result === 'string' ? result : key;
      },
      setLang: (lang) => set({ lang }),
    }),
    {
      name:    'pasifik-user-lang',
      storage: createJSONStorage(() =>
        typeof window !== 'undefined'
          ? localStorage
          : { getItem: () => null, setItem: () => {}, removeItem: () => {} }
      ),
    }
  )
);